export const LANGS = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
];

// utils/schemesData.js
export const GOVERNMENT_SCHEMES = [
  {
    sector: 'Direct Income Support',
    icon: '💰',
    color: 'from-emerald-500 to-green-600',
    items: [
      {
        id: 's1',
        titles: {
          en: 'PM-KISAN: ₹6,000 Annual Direct Benefit Transfer',
          hi: 'पीएम-किसान: ₹6,000 वार्षिक प्रत्यक्ष लाभ हस्तांतरण',
          te: 'పిఎం-కిసాన్: ₹6,000 వార్షిక ప్రత్యక్ష ప్రయోజన బదిలీ',
        },
        description: 'Direct bank transfer of ₹2,000 every 4 months to all landholding farmers. Over 9.7 crore farmers benefited in 20th installment with ₹3.69 lakh crore disbursed till date.',
        benefits: '₹6,000/year',
        eligibility: 'All landholding farmers',
        source: 'PM-KISAN Portal',
        url: 'https://pmkisan.gov.in/',
        ts: '2025-09-10',
        badge: 'Universal',
        amount: '₹6,000',
      },
      {
        id: 's2',
        titles: {
          en: 'PM Kisan Maan-Dhan: ₹3,000 Monthly Pension',
          hi: 'पीएम किसान मान-धन: ₹3,000 मासिक पेंशन',
          te: 'పిఎం కిసాన్ మాన్-ధన్: ₹3,000 నెలవారీ పెన్షన్',
        },
        description: 'Monthly pension scheme for small and marginal farmers after age 60. Low monthly contribution ranging from ₹55 to ₹200 based on entry age.',
        benefits: '₹3,000/month after 60',
        eligibility: 'Age 18-40, Small farmers',
        source: 'myScheme Portal',
        url: 'https://www.myscheme.gov.in/schemes/pmkmy',
        ts: '2025-09-10',
        badge: 'Pension',
        amount: '₹3,000',
      },
    ],
  },
  {
    sector: 'Crop Insurance',
    icon: '🛡️',
    color: 'from-blue-500 to-indigo-600',
    items: [
      {
        id: 's3',
        titles: {
          en: 'PM Fasal Bima Yojana: Comprehensive Crop Insurance',
          hi: 'पीएम फसल बीमा योजना: व्यापक फसल बीमा',
          te: 'పిఎం ఫసల్ బీమా యోజన: సమగ్ర పంట బీమా',
        },
        description: 'World\'s largest crop insurance scheme covering 50+ crops against natural calamities, pests, diseases, and post-harvest losses. Extended till 2025-26.',
        benefits: 'Up to 100% crop value',
        eligibility: 'All farmers with land records',
        source: 'PMFBY Portal',
        url: 'https://pmfby.gov.in/',
        ts: '2025-09-10',
        badge: 'Insurance',
        amount: '2% Premium',
      },
      {
        id: 's4',
        titles: {
          en: 'Weather Based Crop Insurance Scheme',
          hi: 'मौसम आधारित फसल बीमा योजना',
          te: 'వాతావరణ ఆధారిత పంట బీమా పథకం',
        },
        description: 'Restructured weather-based crop insurance providing protection against adverse weather conditions. Uses weather parameters as proxy for crop yields.',
        benefits: 'Weather risk coverage',
        eligibility: 'All farmers',
        source: 'Insurance Companies',
        url: 'https://www.india.gov.in/spotlight/weather-based-crop-insurance-scheme',
        ts: '2025-09-10',
        badge: 'Weather',
        amount: 'Low Premium',
      },
    ],
  },
  {
    sector: 'Credit & Finance',
    icon: '🏦',
    color: 'from-purple-500 to-pink-600',
    items: [
      {
        id: 's5',
        titles: {
          en: 'Kisan Credit Card: 4% Interest Subsidized Loans',
          hi: 'किसान क्रेडिट कार्ड: 4% ब्याज सब्सिडी ऋण',
          te: 'కిసాన్ క్రెడిట్ కార్డ్: 4% వడ్డీ సబ్సిడీ రుణాలు',
        },
        description: 'Flexible credit facility up to ₹3 lakh at subsidized 4% interest rate for crop production, equipment, and agricultural needs with revolving credit facility.',
        benefits: 'Up to ₹3 lakh at 4%',
        eligibility: 'All farmers',
        source: 'SBI Agri Portal',
        url: 'https://sbi.co.in/web/agri-rural/agriculture-banking/government-schemes',
        ts: '2025-09-10',
        badge: 'Credit',
        amount: '4% Interest',
      },
      {
        id: 's6',
        titles: {
          en: 'Agriculture Infrastructure Fund: ₹2 Crore Loans',
          hi: 'कृषि अवसंरचना कोष: ₹2 करोड़ ऋण',
          te: 'వ్యవసాయ మౌలిక సదుపాయాల నిధి: ₹2 కోట్ల రుణాలు',
        },
        description: '3% interest subvention on loans up to ₹2 crore for infrastructure development. ₹33,209 crores sanctioned for 44,912 projects till date.',
        benefits: 'Up to ₹2 crore',
        eligibility: 'FPOs, cooperatives, entrepreneurs',
        source: 'NABARD',
        url: 'https://www.nabard.org/content1.aspx?id=23&catid=23&mid=530',
        ts: '2025-09-10',
        badge: 'Infrastructure',
        amount: '3% Subvention',
      },
    ],
  },
  {
    sector: 'Technology & Digital',
    icon: '📱',
    color: 'from-cyan-500 to-blue-600',
    items: [
      {
        id: 's7',
        titles: {
          en: 'Digital Agriculture Mission: AI-Powered Farming',
          hi: 'डिजिटल कृषि मिशन: एआई संचालित खेती',
          te: 'డిజిటల్ వ్యవసాయ మిషన్: AI శక్తితో వ్యవసాయం',
        },
        description: 'Union Cabinet approved mission with ₹2,817 crore budget. Provides AI, blockchain, IoT, drone technology, real-time advisory, and precision farming apps.',
        benefits: 'Tech support worth ₹5,000+/year',
        eligibility: 'All registered farmers',
        source: 'Digital India Portal',
        url: 'https://services.india.gov.in/service/listing/agriculture',
        ts: '2025-09-10',
        badge: 'Digital',
        amount: 'Free Access',
      },
      {
        id: 's8',
        titles: {
          en: 'eNAM: National Agriculture Market Platform',
          hi: 'ई-नाम: राष्ट्रीय कृषि बाजार मंच',
          te: 'ఈ-నాం: జాతీయ వ్యవసాయ మార్కెట్ వేదిక',
        },
        description: 'Pan-India electronic trading portal networking existing APMC mandis. Provides transparent price discovery, online trading, and direct market access.',
        benefits: 'Better price realization',
        eligibility: 'All farmers & traders',
        source: 'eNAM Portal',
        url: 'https://www.enam.gov.in/',
        ts: '2025-09-10',
        badge: 'Market',
        amount: 'Free Platform',
      },
    ],
  },
  {
    sector: 'Water & Solar',
    icon: '💧',
    color: 'from-orange-500 to-red-600',
    items: [
      {
        id: 's9',
        titles: {
          en: 'PM KUSUM: Solar Pump & Panel Subsidies',
          hi: 'पीएम कुसुम: सोलर पंप व पैनल सब्सिडी',
          te: 'పిఎం కుసుమ్: సోలార్ పంప్ & ప్యానెల్ సబ్సిడీలు',
        },
        description: 'Provides 60% subsidy on solar water pumps and panels. Farmers can sell excess power generated back to the grid, creating additional income source.',
        benefits: '60% subsidy + income',
        eligibility: 'All farmers',
        source: 'MNRE Portal',
        url: 'https://www.mnre.gov.in/solar/schemes/',
        ts: '2025-09-10',
        badge: 'Solar',
        amount: '60% Subsidy',
      },
      {
        id: 's10',
        titles: {
          en: 'PM Krishi Sinchai Yojana: Drip Irrigation Support',
          hi: 'पीएम कृषि सिंचाई योजना: ड्रिप सिंचाई सहायता',
          te: 'పిఎం కృషి సిన్చయ్ యోజన: డ్రిప్ సేద్య మద్దతు',
        },
        description: 'Per Drop More Crop component providing 45-55% subsidy on drip and sprinkler irrigation systems to enhance water use efficiency.',
        benefits: '45-55% subsidy',
        eligibility: 'All farmers',
        source: 'myScheme Portal',
        url: 'https://www.myscheme.gov.in/schemes/pmksy-pdmc',
        ts: '2025-09-10',
        badge: 'Irrigation',
        amount: '55% Off',
      },
    ],
  },
  {
    sector: 'Fisheries & Allied',
    icon: '🐟',
    color: 'from-blue-400 to-blue-700',
    items: [
      {
        id: 's11',
        titles: {
          en: 'PM Matsya Sampada Yojana: Blue Revolution',
          hi: 'पीएम मत्स्य संपदा योजना: नीली क्रांति',
          te: 'పిఎం మత్స్య సంపత యోజన: నీలి విప్లవం',
        },
        description: 'Comprehensive fisheries development scheme with ₹20,050 crore investment. Supports aquaculture, infrastructure, processing, and marketing with 39 startups approved.',
        benefits: 'Up to ₹1.5L subsidy',
        eligibility: 'Fishermen & entrepreneurs',
        source: 'PMMSY Portal',
        url: 'https://pmmsy.dof.gov.in/',
        ts: '2025-09-10',
        badge: 'Fisheries',
        amount: '₹1.5L Max',
      },
      {
        id: 's12',
        titles: {
          en: 'PM-MKSSY: Fisheries Cooperative Support',
          hi: 'पीएम-एमकेएसएसवाई: मत्स्य सहकारिता सहायता',
          te: 'పిఎం-MKSSY: మత్స్య సహకార మద్దతు',
        },
        description: 'Sub-scheme of PMMSY supporting 5,500 primary fisheries cooperatives with mentoring, capacity building, and financial support for collective farming.',
        benefits: 'Cooperative strengthening',
        eligibility: 'Fisheries cooperatives',
        source: 'PM-MKSSY Portal',
        url: 'https://pmmkssy.dof.gov.in/',
        ts: '2025-09-10',
        badge: 'Cooperative',
        amount: 'Grant Support',
      },
    ],
  },
  {
    sector: 'Organic & Sustainable',
    icon: '🌱',
    color: 'from-green-600 to-green-900',
    items: [
      {
        id: 's13',
        titles: {
          en: 'Paramparagat Krishi Vikas Yojana: Organic Farming',
          hi: 'परम्परागत कृषि विकास योजना: जैविक खेती',
          te: 'పారంపరిగత కృషి వికాస్ యోజన: సేంద్రిય వ్యవసాయం',
        },
        description: 'Promotes cluster-based organic farming with ₹31,500 per hectare support for three-year organic clusters including certification and marketing assistance.',
        benefits: '₹31,500 per hectare',
        eligibility: 'Organic farmer groups',
        source: 'Organic Farming Portal',
        url: 'https://www.india.gov.in/spotlight/paramparagat-krishi-vikas-yojana',
        ts: '2025-09-10',
        badge: 'Organic',
        amount: '₹31.5K/ha',
      },
      {
        id: 's14',
        titles: {
          en: 'Soil Health Card Scheme: Nutrient Management',
          hi: 'मृदा स्वास्थ्य कार्ड योजना: पोषक प्रबंधन',
          te: 'మట్టి ఆరోగ్య కార్డ్ పథకం: పోషక నిర్వహణ',
        },
        description: 'Bi-annual soil nutrient analysis reports with tailored fertilizer recommendations to promote balanced fertilizer use and soil health improvement.',
        benefits: 'Free soil testing',
        eligibility: 'All farmers',
        source: 'Agriculture Portal',
        url: 'https://www.india.gov.in/spotlight/soil-health-card',
        ts: '2025-09-10',
        badge: 'Soil Health',
        amount: 'Free Service',
      },
    ],
  },
  {
    sector: 'Machinery & Equipment',
    icon: '🚜',
    color: 'from-red-500 to-orange-600',
    items: [
      {
        id: 's15',
        titles: {
          en: 'Sub-Mission on Agricultural Mechanization',
          hi: 'कृषि यांत्रीकरण पर उप-मिशन',
          te: 'వ్యవసాయ యంత్రీకరణ ఉప-మిషన్',
        },
        description: 'Direct Benefit Transfer for farm machinery with 40-60% subsidy on tractors, harvesters, implements, and custom hiring centers to reduce labor costs.',
        benefits: '40-60% subsidy',
        eligibility: 'All farmers',
        source: 'DBT Agriculture',
        url: 'https://agrimachinery.nic.in/',
        ts: '2025-09-10',
        badge: 'Machinery',
        amount: '60% Max',
      },
    ],
  },
  {
    sector: 'Market Support',
    icon: '📈',
    color: 'from-indigo-500 to-purple-600',
    items: [
      {
        id: 's16',
        titles: {
          en: 'PM-AASHA: Minimum Support Price Scheme',
          hi: 'पीएम-आशा: न्यूनतम समर्थन मूल्य योजना',
          te: 'పిఎం-ఆశా: కనీస మద్దతు ధర పథకం',
        },
        description: 'Ensures remunerative prices for farmers through MSP for notified crops with ₹20,000 crore budget benefiting 120 million farmers across India.',
        benefits: 'MSP guarantee',
        eligibility: 'All crop farmers',
        source: 'Agriculture Ministry',
        url: 'https://www.myscheme.gov.in/schemes/pmaasha',
        ts: '2025-09-10',
        badge: 'MSP',
        amount: 'Price Support',
      },
      {
        id: 's17',
        titles: {
          en: '10,000 FPO Scheme: Farmer Collectives',
          hi: '10,000 एफपीओ योजना: किसान सामूहिक',
          te: '10,000 FPO పథకం: రైతు సమూహాలు',
        },
        description: 'Formation of Farmer Producer Organizations with grants up to ₹18 lakh per FPO in phases for collective bargaining and shared technology access.',
        benefits: 'Up to ₹18 lakh/FPO',
        eligibility: 'Farmer groups',
        source: 'NABARD',
        url: 'https://www.nabard.org/auth/writereaddata/tender/1608201411253000-FPO-Guidelines.pdf',
        ts: '2025-09-10',
        badge: 'Collective',
        amount: '₹18L Grant',
      },
    ],
  },
];

